{% set name = "opentelemetry-instrumentation-psycopg2" %}
{% set version = "0.55b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_psycopg2-{{ version }}.tar.gz
  sha256: fa7035b328b77196e03a631921e0fc10f4b1d4d36d9b66fe9a38971bb88af6d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - psycopg2
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.55b1
    - opentelemetry-instrumentation-dbapi ==0.55b1
    # - psycopg2 >=2.7.3.1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - psycopg2-binary >=2.7.3.1
    - python {{ python_min }}

about:
  summary: OpenTelemetry psycopg2 instrumentation
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-psycopg2
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/opentelemetry-api
    - mariusvniekerk
    - rxm7706
